# Generated by Django 5.1.3 on 2024-12-24 01:00

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoAssociadoLegalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para o certificado de associado legal.', upload_to=app_automacoes.models.upload_to_certificado_associado_legal, verbose_name='PDF Base para Certificado de Associado Legal')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoAtividadePesqueiraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de Atividade Pesqueira.', upload_to=app_automacoes.models.upload_to_declaracao_atividade_pesqueira, verbose_name='PDF Base para Declaração de Atividade Pesqueira')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoHiposuficienciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de Atividade Pesqueira.', upload_to=app_automacoes.models.upload_to_declaracao_hipossuficiencia, verbose_name='PDF Base para Declaração de Hipossuficiência')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='ProcuracaoJuridicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a procuração jurídica.', upload_to=app_automacoes.models.upload_to_procuracao_juridica, verbose_name='PDF Base para Procuração Jurídica')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='TermoCompromissoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para o termo de compromisso.', upload_to=app_automacoes.models.upload_to_termo_compromisso, verbose_name='PDF Base para Termo de Compromisso')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
