# Generated by Django 5.1.7 on 2025-04-04 21:10

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboAnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Recibos/Anuidades.', upload_to=app_automacoes.models.upload_to_procuracao_juridica, verbose_name='PDF Base para Recibo Anuidade')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
