# Generated by Django 5.1.3 on 2024-12-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0002_certificadoassociadolegalmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeclaracaoHiposuficienciaModel',
            new_name='DeclaracaoHipossuficienciaModel',
        ),
    ]
