# Generated by Django 5.1.7 on 2025-04-04 21:22

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0002_reciboanuidademodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciboanuidademodel',
            name='pdf_base',
            field=models.FileField(help_text='Substituirá o arquivo base atual para a Recibos/Anuidades.', upload_to=app_automacoes.models.upload_to_recibo_anuidade, verbose_name='PDF Base para Recibo Anuidade'),
        ),
    ]
