# Generated by Django 5.1.7 on 2025-04-05 00:55

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0003_alter_reciboanuidademodel_pdf_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboServicoExtraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Recibos/Serviço Extra.', upload_to=app_automacoes.models.upload_to_recibo_servico_extra, verbose_name='PDF Base para Recibo Serviço Extra')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
