# Generated by Django 5.1.7 on 2025-05-10 02:44

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0004_reciboservicoextramodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteirinhaAssociadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Carteirinha do Associado.', upload_to=app_automacoes.models.upload_to_carteirinha_apapesc, verbose_name='PDF Base para Carteirinha do Associado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
