# Generated by Django 5.1.7 on 2025-05-30 21:32

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0006_cobrancaanuidademodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcuracaoAdministrativaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a procuração administrativa.', upload_to=app_automacoes.models.upload_to_procuracao_administrativa, verbose_name='PDF Base para Procuração Administrativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
