# Generated by Django 5.1.7 on 2025-05-30 23:45

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0007_procuracaoadministrativamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoDireitoImagemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a autorização de direito de imagem.', upload_to=app_automacoes.models.uoload_to_autorizacao_direito_imagem, verbose_name='PDF Base para Autorização de Direito de Imagem')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
