# Generated by Django 5.1.7 on 2025-05-31 00:04

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0008_autorizacaodireitoimagemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoAcessoGovModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a autorização de acesso ao Gov.', upload_to=app_automacoes.models.upload_to_autorizacao_acesso_gov, verbose_name='PDF Base para Autorização de Acesso ao Gov')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
