# Generated by Django 5.1.7 on 2025-05-31 00:48

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0009_autorizacaoacessogovmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoDesfiliacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de desfiliação.', upload_to=app_automacoes.models.upload_to_declaracao_desfiliacao, verbose_name='PDF Base para Declaração de Desfiliação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
