# Generated by Django 5.1.7 on 2025-05-31 23:28

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0010_declaracaodesfiliacaomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireitosDeveres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para Regramentos Direitos e Deveres.', upload_to=app_automacoes.models.upload_to_direitos_deveres, verbose_name='PDF Base para Regramentos Direitos e Deveres')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
