# Generated by Django 5.1.7 on 2025-06-06 21:22

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0011_direitosdeveres'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiradaDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para declaração de retiradda de documentos.', upload_to=app_automacoes.models.upload_to_retirada_documentos, verbose_name='PDF Base para declaração de retiradda de documentos')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
