# Generated by Django 5.1.3 on 2025-03-17 23:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associacao', '0001_initial'),
        ('app_associados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaINSSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveSmallIntegerField(choices=[(4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro')], verbose_name='Mês de Referência')),
                ('ano', models.PositiveIntegerField(default=2025, verbose_name='Ano')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('emitido', 'Emitido'), ('enviado', 'Enviado')], default='pendente', max_length=10, verbose_name='Status')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_inss', to='app_associados.associadomodel', verbose_name='Associado')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
            ],
            options={
                'verbose_name': 'Guia INSS',
                'verbose_name_plural': 'Guias INSS',
                'ordering': ['ano', 'mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='TarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Breve Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data Conlusão')),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('hora_limite', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('devolvida', 'Devolvida'), ('arquivada', 'Arquivada'), ('desarquivada', 'Desarquivada')], default='pendente', max_length=20, verbose_name='status da Tarefa')),
                ('categoria', models.CharField(choices=[('administrativa', 'Administrativa'), ('associado', 'Associado'), ('integrante', 'Integrante'), ('sistema', 'Sistema'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=20, verbose_name='Prioridade')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Anotações')),
                ('arquivada', models.BooleanField(default=False, verbose_name='Arquivada')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associados.associadomodel', verbose_name='Associado')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsaveis', models.ManyToManyField(related_name='tarefas_atribuidas', to='app_associacao.integrantesmodel', verbose_name='Responsáveis')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=50, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status Novo')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Alteração')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associacao.integrantesmodel', verbose_name='Alterado por')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='app_tarefas.tarefamodel', verbose_name='Tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoResponsaveisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Alteração')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associacao.integrantesmodel', verbose_name='Alterado por')),
                ('responsaveis_anteriores', models.ManyToManyField(related_name='responsaveis_anteriores', to='app_associacao.integrantesmodel', verbose_name='Responsáveis Anteriores')),
                ('responsaveis_novos', models.ManyToManyField(related_name='responsaveis_novos', to='app_associacao.integrantesmodel', verbose_name='Responsáveis Novos')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_responsaveis', to='app_tarefas.tarefamodel', verbose_name='Tarefa')),
            ],
        ),
    ]
