# Generated by Django 5.1.3 on 2024-12-25 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0006_integrantesmodel_oab'),
        ('app_associados', '0001_initial'),
        ('app_tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='TarefaModel',
        ),
    ]
