# Generated by Django 5.1.7 on 2025-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiainssmodel',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('emitido', 'Emitido'), ('enviado', 'Enviado'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='Status'),
        ),
    ]
