# Generated by Django 5.1.7 on 2025-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0002_alter_guiainssmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiainssmodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guiainssmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
