# Generated by Django 5.1.3 on 2024-12-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0002_rename_tarefa_tarefamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefamodel',
            name='hora_limite',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefamodel',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('devolvida', 'Devolvida'), ('arquivada', 'Arquivada'), ('desarquivada', 'Desarquivada')], default='pendente', max_length=20, verbose_name='status da Tarefa'),
        ),
    ]
