# Generated by Django 5.1.7 on 2025-04-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0003_guiainssmodel_deleted_guiainssmodel_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiainssmodel',
            options={'default_manager_name': 'objects', 'ordering': ['ano', 'mes_referencia'], 'verbose_name': 'Guia INSS', 'verbose_name_plural': 'Guias INSS'},
        ),
    ]
