# Generated by Django 5.1.3 on 2024-12-27 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0008_alter_integrantesmodel_email'),
        ('app_tarefas', '0003_tarefamodel_data_limite_tarefamodel_hora_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=50, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status Novo')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Alteração')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associacao.integrantesmodel', verbose_name='Alterado por')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='app_tarefas.tarefamodel', verbose_name='Tarefa')),
            ],
        ),
    ]
