# Generated by Django 5.1.3 on 2024-12-27 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0008_alter_integrantesmodel_email'),
        ('app_tarefas', '0004_historicostatusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoResponsaveisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Alteração')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associacao.integrantesmodel', verbose_name='Alterado por')),
                ('responsaveis_anteriores', models.ManyToManyField(related_name='responsaveis_anteriores', to='app_associacao.integrantesmodel', verbose_name='Responsáveis Anteriores')),
                ('responsaveis_novos', models.ManyToManyField(related_name='responsaveis_novos', to='app_associacao.integrantesmodel', verbose_name='Responsáveis Novos')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_responsaveis', to='app_tarefas.tarefamodel', verbose_name='Tarefa')),
            ],
        ),
    ]
