# Generated by Django 5.1.7 on 2025-04-17 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0002_alter_associadomodel_recebe_seguro'),
        ('app_tarefas', '0004_alter_guiainssmodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiainssmodel',
            options={'verbose_name': 'Guia de INSS', 'verbose_name_plural': 'Guias de INSS'},
        ),
        migrations.AlterField(
            model_name='guiainssmodel',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guiainssmodel',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('paga', 'Paga'), ('atrasada', 'Atrasada')], default='pendente', max_length=50),
        ),
        migrations.CreateModel(
            name='LancamentoINSSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano de Referência')),
                ('mes', models.PositiveIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mês de Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_inss', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lançamento INSS',
                'verbose_name_plural': 'Lançamentos INSS',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
        migrations.AddField(
            model_name='guiainssmodel',
            name='lancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='app_tarefas.lancamentoinssmodel', verbose_name='Lançamento'),
        ),
        migrations.AlterUniqueTogether(
            name='guiainssmodel',
            unique_together={('lancamento', 'associado')},
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='emitido_por',
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='mes_referencia',
        ),
    ]
