# Generated by Django 5.1.3 on 2024-12-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0005_historicoresponsaveismodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='arquivada',
            field=models.BooleanField(default=False, verbose_name='Arquivada'),
        ),
    ]
