# Generated by Django 5.1.7 on 2025-04-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0005_alter_guiainssmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiainssmodel',
            name='observacoes',
            field=models.CharField(choices=[('validar_acesso', 'Validar Acesso'), ('senha_invalida', 'Senha Inválida'), ('nivel_conta', 'Nível Conta'), ('certo', 'Certo')], default='certo', max_length=50),
        ),
    ]
