# Generated by Django 5.1.3 on 2024-12-28 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0006_tarefamodel_arquivada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
        ),
    ]
