# Generated by Django 5.1.7 on 2025-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0006_guiainssmodel_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentoinssmodel',
            name='mes',
            field=models.PositiveIntegerField(choices=[(4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11')], verbose_name='Mês de Referência'),
        ),
    ]
