# Generated by Django 5.1.3 on 2024-12-28 04:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0007_notificacaomodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaomodel',
            name='lida',
        ),
        migrations.AddField(
            model_name='notificacaomodel',
            name='data_visualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacaomodel',
            name='visualizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacaomodel',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificacaomodel',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacaomodel',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacaomodel',
            name='remetente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
