# Generated by Django 5.1.7 on 2025-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0007_alter_lancamentoinssmodel_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiainssmodel',
            name='observacoes',
            field=models.CharField(blank=True, choices=[('validar_acesso', 'Validar Acesso'), ('senha_invalida', 'Senha Inválida'), ('nivel_conta', 'Nível Conta'), ('certo', 'Certo')], default='certo', max_length=50, null=True),
        ),
    ]
