# Generated by Django 5.1.7 on 2025-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0008_alter_guiainssmodel_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiainssmodel',
            name='observacoes',
            field=models.CharField(blank=True, choices=[('validar_acesso', 'Validar Acesso'), ('senha_invalida', 'Senha Inválida'), ('nivel_conta', 'Nível Conta'), ('sem_login', 'Sem Login'), ('sem_caepf', 'Sem CAEPF'), ('certo', 'Certo')], default='certo', max_length=50, null=True),
        ),
    ]
