# Generated by Django 5.1.3 on 2024-12-28 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0008_remove_notificacaomodel_lida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaomodel',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app_tarefas.tarefamodel', verbose_name='Tarefa Relacionada'),
        ),
    ]
