# Generated by Django 5.1.3 on 2024-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0009_notificacaomodel_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaomodel',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Relacionado'),
        ),
    ]
