# Generated by Django 5.1.7 on 2025-05-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0009_alter_guiainssmodel_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoGuiaINSSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarefas.lancamentoinssmodel')),
                ('ultima_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarefas.guiainssmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lancamento')},
            },
        ),
    ]
