# Generated by Django 5.1.3 on 2024-12-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0010_notificacaomodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
