# Generated by Django 5.1.7 on 2025-05-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0010_progressoguiainssmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='app_tarefas.tarefamodel')),
            ],
        ),
    ]
