# Generated by Django 5.1.3 on 2024-12-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0011_tarefamodel_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacaoModel',
        ),
    ]
