# Generated by Django 5.1.7 on 2025-05-28 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0011_checklistitemmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guiainssmodel',
            name='em_processamento_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_em_processamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiainssmodel',
            name='iniciou_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
