# Generated by Django 5.1.7 on 2025-05-28 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0012_guiainssmodel_em_processamento_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RodadaProcessamentoINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='app_tarefas.lancamentoinssmodel')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaRodadaProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processada_em', models.DateTimeField(auto_now_add=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarefas.guiainssmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_processadas', to='app_tarefas.rodadaprocessamentoinss')),
            ],
            options={
                'unique_together': {('rodada', 'guia')},
            },
        ),
    ]
