# Generated by Django 5.1.3 on 2025-02-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0005_associadomodel_drive_folder_id'),
        ('app_tarefas', '0013_alter_tarefamodel_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaINSSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(choices=[('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro')], max_length=20, verbose_name='Mês de Referência')),
                ('ano', models.PositiveIntegerField(default=2025, verbose_name='Ano da Guia')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('concluida', models.BooleanField(default=False, verbose_name='Guia Concluída')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_inss', to='app_associados.associadomodel', verbose_name='Associado')),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
            ],
            options={
                'verbose_name': 'Guia de INSS',
                'verbose_name_plural': 'Guias de INSS',
                'ordering': ['-ano', 'mes_referencia'],
                'unique_together': {('associado', 'mes_referencia', 'ano')},
            },
        ),
    ]
