# Generated by Django 5.1.3 on 2025-02-26 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0014_guiainssmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiainssmodel',
            options={'ordering': ['ano', 'mes_referencia'], 'verbose_name': 'Guia INSS', 'verbose_name_plural': 'Guias INSS'},
        ),
        migrations.AlterUniqueTogether(
            name='guiainssmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='guiainssmodel',
            name='emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AddField(
            model_name='guiainssmodel',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('emitido', 'Emitido'), ('enviado', 'Enviado')], default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='guiainssmodel',
            name='ano',
            field=models.PositiveIntegerField(default=2025, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='guiainssmodel',
            name='mes_referencia',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro')], verbose_name='Mês de Referência'),
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='concluida',
        ),
        migrations.RemoveField(
            model_name='guiainssmodel',
            name='emitida_por',
        ),
    ]
