# Generated by Django 5.1.7 on 2025-05-29 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0014_alter_rodadaprocessamentoinss_lancamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guiarodadaprocessada',
            name='processado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_processadas_como_executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guiarodadaprocessada',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_processadas_como_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
