# Generated by Django 5.1.7 on 2025-05-29 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0015_guiarodadaprocessada_processado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodadaprocessamentoinss',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='app_tarefas.lancamentoinssmodel'),
        ),
        migrations.CreateModel(
            name='ChecklistITarefastemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('concluido', models.BooleanField(default=False)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens_massas', to='app_tarefas.tarefamodel')),
            ],
        ),
        migrations.CreateModel(
            name='RodadaProcessamentoTarefaMassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que iniciou a rodada')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessamentoTarefaMassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_processada', 'Não Processada'), ('em_processamento', 'Em Processamento'), ('processada', 'Processada')], default='nao_processada', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_processadas_em_massa', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processamentos_em_massa', to='app_tarefas.tarefamodel')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_processadas', to='app_tarefas.rodadaprocessamentotarefamassa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaMassaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recadastramento_dados', 'Recadastramento de Dados'), ('abertura_contas', 'Abertura de Contas'), ('inscricoes_cursos', 'Inscrições em Cursos')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_geradas', models.PositiveIntegerField(default=0)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='rodadaprocessamentotarefamassa',
            name='tarefa_massa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='app_tarefas.tarefamassamodel', verbose_name='Lançamento de Tarefas em Massa'),
        ),
        migrations.AddField(
            model_name='tarefamodel',
            name='massa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_geradas', to='app_tarefas.tarefamassamodel', verbose_name='Lançamento em Massa (opcional)'),
        ),
    ]
