# Generated by Django 5.1.7 on 2025-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0016_alter_rodadaprocessamentoinss_lancamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentotarefamassa',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
