# Generated by Django 5.1.7 on 2025-05-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0005_alter_associadomodel_status'),
        ('app_tarefas', '0017_processamentotarefamassa_iniciado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReapsAnualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2025)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaps_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento REAPS Anual',
                'verbose_name_plural': 'Lançamentos REAPS Anuais',
                'unique_together': {('ano',)},
            },
        ),
        migrations.CreateModel(
            name='ReapsAssociadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('data_realizado', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_associados.associadomodel')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaps_processados', to=settings.AUTH_USER_MODEL)),
                ('reaps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_tarefas.reapsanualmodel')),
            ],
            options={
                'unique_together': {('reaps', 'associado')},
            },
        ),
    ]
