# Generated by Django 5.1.7 on 2025-06-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0018_reapsanualmodel_reapsassociadoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reapsassociadoitem',
            name='pulado_na_rodada',
            field=models.BooleanField(default=False),
        ),
    ]
