# Generated by Django 5.1.7 on 2025-06-10 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0019_reapsassociadoitem_pulado_na_rodada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiainssmodel',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='app_tarefas.lancamentoinssmodel', verbose_name='Lançamento'),
        ),
    ]
