# Generated by Django 5.1.3 on 2025-03-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associacao', '0002_initial'),
        ('app_associados', '0001_initial'),
        ('app_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1500, verbose_name='Nome do Tipo de Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=1500, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(max_length=1500, upload_to='documentos/', verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associacao_documentos', to='app_associacao.associacaomodel')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_associados.associadomodel')),
                ('integrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_associacao.integrantesmodel')),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparticao_documentos', to='app_associacao.reparticoesmodel')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_documentos', to='app_tarefas.tarefamodel')),
                ('tipo_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documentos.tipodocumentomodel', verbose_name='Tipo de Documento')),
            ],
        ),
    ]
