# Generated by Django 5.1.7 on 2025-05-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0001_initial'),
        ('app_servicos', '0016_alter_servicoextraassociadomodel_extra_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='extra_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_servicos.extraassociadomodel'),
        ),
    ]
