# Generated by Django 5.1.7 on 2025-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0002_documento_extra_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentomodel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
