# Generated by Django 5.1.7 on 2025-05-31 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0003_tipodocumentomodel_descricao'),
        ('app_embarcacoes', '0006_embarcacoesmodel_seguro_dpem_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='embarcacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_embarcacoes.embarcacoesmodel'),
        ),
    ]
