# Generated by Django 5.1.3 on 2024-12-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0003_alter_documento_nome_alter_tipodocumentomodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(max_length=1500, upload_to='documentos/', verbose_name='Arquivo'),
        ),
    ]
