# Generated by Django 5.1.3 on 2024-12-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_alter_integrantesmodel_user'),
        ('app_documentos', '0004_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='reparticao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparticao_documentos', to='app_associacao.reparticoesmodel'),
        ),
    ]
