# Generated by Django 5.1.7 on 2025-06-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0005_alter_associadomodel_status'),
        ('app_documentos', '0004_documento_embarcacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpDocDriveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='temp_docs/')),
                ('nome_final', models.CharField(blank=True, max_length=500)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_drivefolder', to='app_associados.associadomodel')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_documentos.tipodocumentomodel')),
            ],
        ),
    ]
