# Generated by Django 5.1.7 on 2025-06-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0005_updocdrivemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumentomodel',
            name='tipo',
            field=models.CharField(max_length=1500, unique=True, verbose_name='Nome do Tipo de Documento'),
        ),
    ]
