# Generated by Django 5.1.3 on 2024-12-30 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0005_documento_reparticao'),
        ('app_tarefas', '0012_delete_notificacaomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_documentos', to='app_tarefas.tarefamodel'),
        ),
    ]
