# Generated by Django 5.1.7 on 2025-06-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0006_alter_tipodocumentomodel_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='repositorio_padrao',
            field=models.BooleanField(default=False, verbose_name='É Documento do Repositório?'),
        ),
    ]
