# Generated by Django 5.1.3 on 2025-03-17 23:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associacao', '0001_initial'),
        ('app_associados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True, verbose_name='Ano da Anuidade')),
                ('valor_anuidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Anuidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anuidade',
                'verbose_name_plural': 'Anuidades',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='TipoDespesaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Tipo de Despesa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Tipo de Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnuidadeAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('pago', models.BooleanField(default=False, verbose_name='Anuidade Paga')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades_associados', to='app_associados.associadomodel')),
                ('anuidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades_associados', to='app_finances.anuidademodel')),
            ],
            options={
                'verbose_name': 'Anuidade do Associado',
                'verbose_name_plural': 'Anuidades dos Associados',
                'ordering': ['associado'],
                'unique_together': {('anuidade', 'associado')},
            },
        ),
        migrations.CreateModel(
            name='DescontoAnuidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('motivo', models.TextField(verbose_name='Motivo do Desconto')),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('anuidade_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='app_finances.anuidadeassociado', verbose_name='Anuidade Associado')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
            ],
            options={
                'verbose_name': 'Desconto na Anuidade',
                'verbose_name_plural': 'Descontos nas Anuidades',
            },
        ),
        migrations.CreateModel(
            name='DespesaAssociacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Despesa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número da Nota Fiscal')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Lançamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Despesa Paga')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registros', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='app_finances.tipodespesamodel', verbose_name='Tipo de Despesa')),
            ],
            options={
                'verbose_name': 'Despesa da Associação',
                'verbose_name_plural': 'Despesas das Associações',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='DespesaAlteracaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='app_finances.despesaassociacaomodel', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Alteração de Despesa',
                'verbose_name_plural': 'Alterações de Despesas',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='EntradaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro')], max_length=10, verbose_name='Forma de Pagamento')),
                ('parcelamento', models.CharField(choices=[('avista', 'À Vista'), ('entrada_1x', 'Entrada + 1x'), ('entrada_2x', 'Entrada + 2x')], max_length=15, verbose_name='Parcelamento')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='Status do Pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='app_finances.tiposervicomodel', verbose_name='Tipo de Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaAlteracaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('entrada', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='app_finances.entradafinanceira', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Alteração de Entrada',
                'verbose_name_plural': 'Alterações de Entradas',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('pago', models.BooleanField(default=False, verbose_name='Parcela Paga')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='app_finances.entradafinanceira')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_finances.entradafinanceira')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_finances.parcela')),
            ],
        ),
    ]
