# Generated by Django 5.1.3 on 2025-02-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0005_associadomodel_drive_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True, verbose_name='Ano da Anuidade')),
                ('valor_anuidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Anuidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anuidade',
                'verbose_name_plural': 'Anuidades',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='AnuidadeAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pro_rata', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pro-Rata')),
                ('pago', models.BooleanField(default=False, verbose_name='Anuidade Paga')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades_associados', to='app_associados.associadomodel')),
                ('anuidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades_associados', to='app_finances.anuidademodel')),
            ],
            options={
                'verbose_name': 'Anuidade do Associado',
                'verbose_name_plural': 'Anuidades dos Associados',
                'ordering': ['associado'],
                'unique_together': {('anuidade', 'associado')},
            },
        ),
    ]
