# Generated by Django 5.1.3 on 2025-03-17 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradafinanceira',
            old_name='valor_pago',
            new_name='valor_pagamento',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='valor_pago',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='parcela',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='anuidade_associado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_finances.anuidadeassociado'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PagamentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_finances.entradafinanceira')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_finances.parcela')),
            ],
        ),
    ]
