# Generated by Django 5.1.3 on 2025-02-02 18:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuidadeassociado',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago'),
        ),
    ]
