# Generated by Django 5.1.3 on 2025-02-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0002_anuidadeassociado_valor_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('anuidade_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_finances.anuidadeassociado')),
            ],
        ),
    ]
