# Generated by Django 5.1.7 on 2025-03-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0002_rename_valor_pago_entradafinanceira_valor_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceira',
            name='valor_pagamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
    ]
