# Generated by Django 5.1.7 on 2025-03-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0003_alter_entradafinanceira_valor_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceira',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', editable=False, max_length=10, verbose_name='Status do Pagamento'),
        ),
    ]
