# Generated by Django 5.1.7 on 2025-03-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0004_alter_entradafinanceira_status_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceira',
            name='parcelamento',
            field=models.CharField(choices=[('avista', 'Pagamento à Vista'), ('duas_parcelas', 'Duas Parcelas'), ('tres_parcelas', 'Três Parcelas')], max_length=15, verbose_name='Parcelamento'),
        ),
    ]
