# Generated by Django 5.1.3 on 2025-02-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0005_associadomodel_drive_folder_id'),
        ('app_finances', '0005_tipodespesamodel_despesaassociacaomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesaassociacaomodel',
            name='associacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='app_associados.associadomodel'),
        ),
    ]
