# Generated by Django 5.1.7 on 2025-03-18 19:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0005_alter_entradafinanceira_parcelamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentoentrada',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='pagamentoentrada',
            name='valor_pagamento',
        ),
        migrations.AddField(
            model_name='pagamentoentrada',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamentoentrada',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamentoentrada',
            name='data_pagamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
