# Generated by Django 5.1.3 on 2025-02-25 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0006_alter_despesaassociacaomodel_associacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescontoAnuidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('motivo', models.TextField(verbose_name='Motivo do Desconto')),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('anuidade_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='app_finances.anuidadeassociado', verbose_name='Anuidade Associado')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
            ],
            options={
                'verbose_name': 'Desconto na Anuidade',
                'verbose_name_plural': 'Descontos nas Anuidades',
            },
        ),
    ]
