# Generated by Django 5.1.7 on 2025-03-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0006_remove_pagamentoentrada_parcela_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcela',
        ),
    ]
