# Generated by Django 5.1.7 on 2025-03-18 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0007_delete_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceira',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
