# Generated by Django 5.1.7 on 2025-03-23 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0010_alter_entradaalteracaomodel_entrada_and_more'),
        ('app_servicos', '0005_remove_servicohistoricomodel_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradafinanceira',
            name='servico_extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_relacionada', to='app_servicos.servicoextraassociadomodel', verbose_name='Serviço Extra'),
        ),
    ]
