# Generated by Django 5.1.7 on 2025-03-23 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0011_entradafinanceira_servico_extra'),
        ('app_servicos', '0005_remove_servicohistoricomodel_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceira',
            name='servico_extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_servico_extra', to='app_servicos.servicoextraassociadomodel', verbose_name='Serviço Extra Vinculado'),
        ),
    ]
