# Generated by Django 5.1.7 on 2025-05-14 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0012_alter_entradafinanceira_servico_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaassociacaomodel',
            name='comprovante_nota',
            field=models.FileField(blank=True, help_text='Upload do comprovante em PDF, JPG ou PNG.', null=True, upload_to='comprovantes_despesas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante / Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='despesaassociacaomodel',
            name='data_upload_comprovante',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data do Upload do Comprovante'),
        ),
    ]
