# Generated by Django 5.1.7 on 2025-06-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0013_despesaassociacaomodel_comprovante_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicomodel',
            name='natureza',
            field=models.CharField(choices=[('emissao_documento', 'Emissão de Documento'), ('servico_consultoria', 'Serviço de Consultoria'), ('servico_geral', 'Serviço Geral')], default='servico_geral', max_length=50, verbose_name='Natureza do Serviço'),
        ),
    ]
