# Generated by Django 5.1.7 on 2025-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0014_tiposervicomodel_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicomodel',
            name='natureza',
            field=models.CharField(blank=True, choices=[('emissao_documento', 'Emissão de Documento'), ('servico_consultoria', 'Serviço de Consultoria'), ('servico_geral', 'Serviço Geral')], max_length=50, verbose_name='Natureza do Serviço'),
        ),
    ]
