# Generated by Django 5.1.7 on 2025-04-05 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0002_alter_associadomodel_recebe_seguro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('seguro_defeso', 'Seguro Defeso'), ('seguro_tainha', 'Seguro Tainha'), ('seguro_camarao', 'Seguro Camarão')], max_length=80)),
                ('lei_federal', models.CharField(blank=True, max_length=150, null=True)),
                ('instrucao_normativa', models.CharField(blank=True, max_length=150, null=True)),
                ('portaria', models.CharField(blank=True, max_length=150, null=True)),
                ('ano_concessao', models.PositiveIntegerField(default=2025)),
                ('estado', models.CharField(max_length=2)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('anotacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'unique_together': {('nome', 'ano_concessao', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ControleBeneficioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.CharField(choices=[('EM_PREPARO', 'Em Preparo'), ('PROTOCOLADO', 'Protocolado'), ('EM_ANALISE', 'Em Análise'), ('RECURSO', 'Recurso'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('ARQUIVADO', 'Arquivado')], default='EM_PREPARO', max_length=20)),
                ('data_entrada', models.DateField()),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('anotacoes_exigencias', models.TextField(blank=True, null=True)),
                ('anotacoes_gerais', models.TextField(blank=True, null=True)),
                ('resultado_final', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='app_associados.associadomodel')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='app_beneficios.beneficiomodel')),
            ],
            options={
                'verbose_name': 'Controle de Benefício',
                'verbose_name_plural': 'Controle de Benefícios',
                'ordering': ['-data_entrada'],
                'unique_together': {('associado', 'beneficio')},
            },
        ),
        migrations.CreateModel(
            name='ControleBeneficioHistoricoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('campo_alterado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_beneficios.controlebeneficiomodel')),
            ],
            options={
                'ordering': ['-alterado_em'],
            },
        ),
    ]
