# Generated by Django 5.1.7 on 2025-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficios', '0002_alter_beneficiomodel_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebeneficiomodel',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
