# Generated by Django 5.1.7 on 2025-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficios', '0004_controlebeneficiomodel_comprovante_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebeneficiomodel',
            name='comprovante_protocolo',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_beneficio/', verbose_name='Comprovante do Protocolo'),
        ),
    ]
