# Generated by Django 5.1.7 on 2025-04-05 20:52

import app_beneficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficios', '0005_alter_controlebeneficiomodel_comprovante_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebeneficiomodel',
            name='comprovante_protocolo',
            field=models.FileField(blank=True, null=True, upload_to=app_beneficios.models.protocolo_upload_path, verbose_name='Comprovante do Protocolo'),
        ),
    ]
