# Generated by Django 5.1.7 on 2025-04-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficios', '0006_alter_controlebeneficiomodel_comprovante_protocolo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlebeneficiohistoricomodel',
            options={'ordering': ['-alterado_em'], 'verbose_name': 'Histórico de Alteração', 'verbose_name_plural': 'Históricos de Alterações'},
        ),
    ]
