# Generated by Django 5.1.7 on 2025-04-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficios', '0007_alter_controlebeneficiohistoricomodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebeneficiomodel',
            name='status_pedido',
            field=models.CharField(choices=[('EM_PREPARO', 'Em Preparo'), ('PROTOCOLADO', 'Protocolado'), ('EXIGENCIA', 'Exigência'), ('EM_ANALISE', 'Em Análise'), ('RECURSO', 'Recurso'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('ARQUIVADO', 'Arquivado')], default='EM_PREPARO', max_length=20),
        ),
    ]
