# Generated by Django 5.1.7 on 2025-05-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficios', '0008_alter_controlebeneficiomodel_status_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevaProcessamentoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrição da Leva')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado', models.BooleanField(default=False, verbose_name='Leva Encerrada')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levas_processamento', to='app_beneficios.beneficiomodel')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControleLevaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizou_itens', to=settings.AUTH_USER_MODEL)),
                ('controle_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_beneficios.controlebeneficiomodel')),
                ('em_processamento_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processando_itens', to=settings.AUTH_USER_MODEL)),
                ('leva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_beneficios.levaprocessamentobeneficio')),
            ],
        ),
    ]
