# Generated by Django 5.1.7 on 2025-03-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_embarcacoes', '0004_embarcacoesmodel_ano_contrucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_nome', models.CharField(choices=[('MAPA', 'Ministério da Agricultura, Pecuária e Abastecimento'), ('IBAMA', 'IBAMA'), ('MMA', 'Ministério do Meio Ambiente'), ('SPU', 'Secretaria do Patrimônio da União')], max_length=50)),
                ('licenca_nome', models.CharField(choices=[('registro_embarcacao', 'Certificado de Registro e Autorização de Embarcação Pesqueira'), ('licenca_ambiental', 'Licença Ambiental'), ('outorga', 'Outorga de Uso de Recursos Hídricos')], max_length=50)),
                ('num_processo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Processo')),
                ('num_atoAdmConcede', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Ato Administrativo')),
                ('codigo_frota', models.CharField(blank=True, max_length=50, null=True)),
                ('inscricao_aut_naval', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade_permissionamento', models.TextField(blank=True, null=True)),
                ('validade_inicial', models.DateField()),
                ('validade_final', models.DateField()),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('embarcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_embarcacoes.embarcacoesmodel')),
            ],
            options={
                'verbose_name': 'Licença de Embarcação',
                'verbose_name_plural': 'Licenças de Embarcações',
            },
        ),
    ]
