# Generated by Django 5.1.7 on 2025-03-31 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0005_rename_ano_contrucao_embarcacoesmodel_ano_construcao'),
        ('app_licencas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencasmodel',
            name='embarcacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='app_embarcacoes.embarcacoesmodel'),
        ),
    ]
