# Generated by Django 5.1.7 on 2025-03-22 02:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0001_initial'),
        ('app_finances', '0010_alter_entradaalteracaomodel_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAssociadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('senha_gov', models.CharField(blank=True, help_text='Senha criptografada para segurança.', max_length=128, null=True)),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\d{5}-\\d{4}$', 'Número inválido. O telefone deve conter 10 ou 11 dígitos, ex: (48)99999-9999.')])),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('status_etapa', models.CharField(choices=[('pendente', 'Pendente'), ('protocolado', 'Protocolado'), ('exigencia', 'Exigência'), ('cumprimento', 'Cumprimento'), ('conclusao', 'Conclusão'), ('recurso', 'Recurso')], default='pendente', max_length=20)),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associados.associadomodel', verbose_name='Associado')),
                ('extra_associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_servicos.extraassociadomodel', verbose_name='Extra-associado')),
                ('tipo_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finances.tiposervicomodel')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
