# Generated by Django 5.1.7 on 2025-03-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicomodel',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicomodel',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ServicoHistoricoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_servicos.servicomodel', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Histórico do Serviço',
                'verbose_name_plural': 'Histórico dos Serviços',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
