# Generated by Django 5.1.7 on 2025-03-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_initial'),
        ('app_servicos', '0002_servicomodel_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicomodel',
            name='associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_associacao', to='app_associacao.associacaomodel', verbose_name='Associação'),
        ),
        migrations.AddField(
            model_name='servicomodel',
            name='reparticao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_reparticao', to='app_associacao.reparticoesmodel', verbose_name='Repartição'),
        ),
    ]
