# Generated by Django 5.1.7 on 2025-03-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finances', '0010_alter_entradaalteracaomodel_entrada_and_more'),
        ('app_servicos', '0003_servicomodel_associacao_servicomodel_reparticao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicomodel',
            name='entrada_relacionada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico', to='app_finances.entradafinanceira', verbose_name='Entrada Financeira Vinculada'),
        ),
    ]
