# Generated by Django 5.1.7 on 2025-03-23 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_initial'),
        ('app_associados', '0001_initial'),
        ('app_finances', '0010_alter_entradaalteracaomodel_entrada_and_more'),
        ('app_servicos', '0004_servicomodel_entrada_relacionada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicohistoricomodel',
            name='servico',
        ),
        migrations.CreateModel(
            name='ServicoAssociadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('status_etapa', models.CharField(choices=[('pendente', 'Pendente'), ('protocolado', 'Protocolado'), ('exigencia', 'Exigência'), ('cumprimento', 'Cumprimento'), ('conclusao', 'Conclusão'), ('recurso', 'Recurso')], default='pendente', max_length=20)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_associacao', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associados.associadomodel', verbose_name='Associado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_criados', to=settings.AUTH_USER_MODEL)),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_reparticao', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
                ('tipo_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finances.tiposervicomodel')),
            ],
        ),
        migrations.AddField(
            model_name='servicohistoricomodel',
            name='servico_associado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_servicos.servicoassociadomodel', verbose_name='Serviço'),
        ),
        migrations.CreateModel(
            name='ServicoExtraAssociadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('status_etapa', models.CharField(choices=[('pendente', 'Pendente'), ('protocolado', 'Protocolado'), ('exigencia', 'Exigência'), ('cumprimento', 'Cumprimento'), ('conclusao', 'Conclusão'), ('recurso', 'Recurso')], default='pendente', max_length=20)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_extra_associacao', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_extra_associados', to=settings.AUTH_USER_MODEL)),
                ('extra_associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_servicos.extraassociadomodel', verbose_name='Extra Associado')),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_extra_reparticao', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
                ('tipo_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finances.tiposervicomodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicoModel',
        ),
    ]
