# Generated by Django 5.1.7 on 2025-03-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0006_servicoextraassociadomodel_entrada_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicohistoricomodel',
            name='servico_extra_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_extra', to='app_servicos.servicoextraassociadomodel'),
        ),
    ]
