# Generated by Django 5.1.7 on 2025-03-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0007_servicohistoricomodel_servico_extra_associado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicoassociadomodel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servicoextraassociadomodel',
            name='descricao',
        ),
        migrations.AddField(
            model_name='servicoassociadomodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicoextraassociadomodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicohistoricomodel',
            name='servico_associado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_servicos.servicoassociadomodel', verbose_name='Serviço Associado'),
        ),
    ]
