# Generated by Django 5.1.7 on 2025-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0008_remove_servicoassociadomodel_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoassociadomodel',
            name='status_etapa',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('doc_protocolado', 'Documento Protocolado'), ('doc_analise', 'Documento em Análise'), ('doc_exigencia', 'Documento em Exigência'), ('doc_cumprimento', 'Documento em Cumprimento'), ('doc_recurso', 'Documento em Recurso'), ('doc_deferido', 'Documento Deferido'), ('doc_indeferido', 'Documento Indeferido'), ('servico_andamento', 'Serviço em Andamento'), ('servico_concluido', 'Serviço Concluído'), ('servico_espera', 'Serviço em Espera')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicoextraassociadomodel',
            name='status_etapa',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('doc_protocolado', 'Documento Protocolado'), ('doc_analise', 'Documento em Análise'), ('doc_exigencia', 'Documento em Exigência'), ('doc_cumprimento', 'Documento em Cumprimento'), ('doc_recurso', 'Documento em Recurso'), ('doc_deferido', 'Documento Deferido'), ('doc_indeferido', 'Documento Indeferido'), ('servico_andamento', 'Serviço em Andamento'), ('servico_concluido', 'Serviço Concluído'), ('servico_espera', 'Serviço em Espera')], default='pendente', max_length=20),
        ),
    ]
