# Generated by Django 5.1.7 on 2025-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0009_alter_servicoassociadomodel_status_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoassociadomodel',
            name='natureza_servico',
            field=models.CharField(choices=[('emissao_documento', 'Emissão de Documento'), ('servico_consultoria', 'Serviço de Consultoria'), ('servico_geral', 'Serviço Geral')], default='emissao_documento', max_length=50, verbose_name='Natureza do Serviço'),
        ),
        migrations.AddField(
            model_name='servicoextraassociadomodel',
            name='natureza_servico',
            field=models.CharField(choices=[('emissao_documento', 'Emissão de Documento'), ('servico_consultoria', 'Serviço de Consultoria'), ('servico_geral', 'Serviço Geral')], default='emissao_documento', max_length=50, verbose_name='Natureza do Serviço'),
        ),
    ]
