# Generated by Django 5.1.7 on 2025-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0011_alter_servicoassociadomodel_natureza_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoextraassociadomodel',
            name='natureza_servico',
            field=models.CharField(choices=[('emissao_documento', 'Emissão de Documento'), ('servico_consultoria', 'Serviço de Consultoria'), ('servico_geral', 'Serviço Geral')], max_length=50, verbose_name='Natureza do Serviço'),
        ),
    ]
