# Generated by Django 5.1.7 on 2025-05-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0015_alter_servicoassociadomodel_status_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoextraassociadomodel',
            name='extra_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_extra_associado', to='app_servicos.extraassociadomodel', verbose_name='Extra Associado'),
        ),
    ]
