# Generated by Django 5.1.3 on 2024-12-17 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantesmodel',
            name='associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrantes', to='app_associacao.associacaomodel', verbose_name='Associação'),
        ),
    ]
