# Generated by Django 5.1.3 on 2024-12-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_alter_integrantesmodel_user'),
        ('app_associados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantesmodel',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'solteiro'), ('solteira', 'solteira'), ('casado', 'casado'), ('casada', 'casada'), ('divorciado', 'divorciado'), ('divorciada', 'divorciada'), ('viúvo', 'viúvo'), ('viúva', 'viúva'), ('união estável', 'união estável'), ('separado judicialmente', 'separado judicialmente'), ('separada judicialmente', 'separada judicialmente'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='integrantesmodel',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Não declarado', max_length=100, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='integrantesmodel',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associados.profissoesmodel', verbose_name='Profissão'),
        ),
    ]
