# Generated by Django 5.1.7 on 2025-06-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipiosmodel',
            name='municipio',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
