# Generated by Django 5.1.3 on 2024-12-24 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0004_alter_integrantesmodel_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantesmodel',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP deve estar no formato 00000-000')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='integrantesmodel',
            name='rg_orgao',
            field=models.CharField(blank=True, choices=[('SSP/AC', 'SSP/AC'), ('SSP/AL', 'SSP/AL'), ('SSP/AP', 'SSP/AP'), ('SSP/AM', 'SSP/AM'), ('SSP/BA', 'SSP/BA'), ('SSP/CE', 'SSP/CE'), ('SSP/DF', 'SSP/DF'), ('SSP/ES', 'SSP/ES'), ('SSP/GO', 'SSP/GO'), ('SSP/MA', 'SSP/MA'), ('SSP/MG', 'SSP/MG'), ('SSP/MS', 'SSP/MS'), ('SSP/MT', 'SSP/MT'), ('SSP/PA', 'SSP/PA'), ('SSP/PB', 'SSP/PB'), ('SSP/PE', 'SSP/PE'), ('SSP/PI', 'SSP/PI'), ('SSP/RJ', 'SSP/RJ'), ('SSP/RN', 'SSP/RN'), ('SSP/RS', 'SSP/RS'), ('SSP/RO', 'SSP/RO'), ('SSP/RR', 'SSP/RR'), ('SSP/SC', 'SSP/SC'), ('SSP/SP', 'SSP/SP'), ('SSP/SE', 'SSP/SE'), ('SSP/TO', 'SSP/TO'), ('UF', 'UF'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='RG-Orgão Emissor'),
        ),
    ]
