# Generated by Django 5.1.3 on 2024-12-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0005_alter_integrantesmodel_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantesmodel',
            name='oab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OAB'),
        ),
    ]
