# Generated by Django 5.1.3 on 2024-12-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0007_alter_reparticoesmodel_municipios_circunscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantesmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Profissonal'),
        ),
    ]
