# Generated by Django 5.1.3 on 2025-01-05 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0008_alter_integrantesmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacaomodel',
            name='diretores',
            field=models.ManyToManyField(blank=True, null=True, related_name='diretores_associacao', to='app_associacao.integrantesmodel', verbose_name='Diretores'),
        ),
        migrations.AlterField(
            model_name='associacaomodel',
            name='fundadores',
            field=models.TextField(blank=True, help_text='Lista de fundadores da associação', null=True, verbose_name='Fundadores'),
        ),
        migrations.AlterField(
            model_name='integrantesmodel',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP deve estar no formato 00000-000')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='integrantesmodel',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Ex: Rua, Servidão, Travessa', max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='reparticoesmodel',
            name='associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparticoes', to='app_associacao.associacaomodel', verbose_name='Associação'),
        ),
        migrations.AlterField(
            model_name='reparticoesmodel',
            name='municipios_circunscricao',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='municipios_circunscricao', to='app_associacao.municipiosmodel', verbose_name='Municipios Circinscrição'),
        ),
    ]
