# Generated by Django 5.1.3 on 2025-01-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0009_alter_associacaomodel_diretores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacaomodel',
            name='diretores',
            field=models.ManyToManyField(blank=True, related_name='diretores_associacao', to='app_associacao.integrantesmodel', verbose_name='Diretores'),
        ),
    ]
