# Generated by Django 5.1.7 on 2025-03-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmbarcacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropulsaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmbarcacoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_proprietario_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Co-Proprietário')),
                ('inscricao_embarcacao', models.CharField(max_length=100, unique=True)),
                ('validade_tie', models.DateField(verbose_name='Validade TIE')),
                ('nome_embarcacao', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=100)),
                ('area_navegacao', models.CharField(max_length=100)),
                ('numero_tripulantes', models.PositiveIntegerField()),
                ('numero_passageiros', models.PositiveIntegerField()),
                ('cumprimento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ab_gt', models.CharField(blank=True, max_length=100, null=True)),
                ('boca', models.CharField(blank=True, max_length=100, null=True)),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('alcool', 'Álcool'), ('diesel', 'Diesel'), ('gas', 'Gás'), ('vela', 'Vela')], max_length=10)),
                ('motor_1', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_1', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_2', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_2', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_3', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_3', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_4', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_4', models.CharField(blank=True, max_length=100, null=True)),
                ('alienacao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5)),
                ('municipio_emissao', models.CharField(max_length=100)),
                ('data_emissao', models.DateField()),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarcacoes', to='app_associados.associadomodel', verbose_name='Proprietário')),
                ('tipo_embarcacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_embarcacoes.tipoembarcacaomodel', verbose_name='Tipo de Embarcação')),
                ('tipo_propulsao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_embarcacoes.tipopropulsaomodel', verbose_name='Tipo de Propulsão')),
            ],
        ),
    ]
