# Generated by Django 5.1.7 on 2025-03-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='destaque_embarcacao_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='popa_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='porte',
            field=models.CharField(choices=[('miuda', 'Miuda'), ('maior porte', 'Maior Porte')], default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='traves_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='embarcacoesmodel',
            name='combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('alcool', 'Álcool'), ('diesel', 'Diesel'), ('gas', 'Gás')], max_length=15),
        ),
    ]
