# Generated by Django 5.1.7 on 2025-03-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0002_embarcacoesmodel_destaque_embarcacao_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacoesmodel',
            name='destaque_embarcacao_img',
            field=models.ImageField(blank=True, null=True, upload_to='embarcacoes/destaques/', verbose_name='Imagem em destaque da embarcação'),
        ),
        migrations.AlterField(
            model_name='embarcacoesmodel',
            name='popa_img',
            field=models.ImageField(blank=True, null=True, upload_to='embarcacoes/popa/', verbose_name='Imagem da Popa'),
        ),
        migrations.AlterField(
            model_name='embarcacoesmodel',
            name='traves_img',
            field=models.ImageField(blank=True, null=True, upload_to='embarcacoes/traves/', verbose_name='Imagem da Trave (lado da embarcação)'),
        ),
    ]
