# Generated by Django 5.1.7 on 2025-03-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0003_alter_embarcacoesmodel_destaque_embarcacao_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='ano_contrucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='arqueacao_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='construtor_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='material_construcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='potencia_hp1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='potencia_hp2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='potencia_hp3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='potencia_hp4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
