# Generated by Django 5.1.7 on 2025-03-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0004_embarcacoesmodel_ano_contrucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embarcacoesmodel',
            old_name='ano_contrucao',
            new_name='ano_construcao',
        ),
    ]
