# Generated by Django 5.1.7 on 2025-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0005_rename_ano_contrucao_embarcacoesmodel_ano_construcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='seguro_dpem_data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='seguro_dpem_numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='seguro_dpen',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5),
        ),
    ]
