# Generated by Django 5.1.7 on 2025-06-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0006_embarcacoesmodel_seguro_dpem_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoembarcacaomodel',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tipopropulsaomodel',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
