# Generated by Django 5.1.7 on 2025-06-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0007_alter_tipoembarcacaomodel_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarcacoesmodel',
            name='ano_construcao',
        ),
        migrations.AlterField(
            model_name='embarcacoesmodel',
            name='combustivel',
            field=models.CharField(choices=[('alcool', 'Álcool'), ('bateria', 'Bateria'), ('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('gas', 'Gás'), ('nao usa', 'Não Usa')], max_length=15),
        ),
    ]
