# Generated by Django 5.1.7 on 2025-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0008_remove_embarcacoesmodel_ano_construcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='ano_construcao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Construção'),
        ),
    ]
