# Generated by Django 5.1.3 on 2025-03-17 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TagArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_source', models.TextField(blank=True, max_length=500, null=True, verbose_name='Fonte da Imagem')),
                ('meta_title', models.CharField(max_length=60)),
                ('content', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.TextField(max_length=160)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False, verbose_name='É VIP')),
                ('old_url', models.SlugField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('research_sources', models.TextField(blank=True, null=True, verbose_name='Fontes de Pesquisa')),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='app_articles.categoryarticlesmodel')),
                ('tags', models.ManyToManyField(blank=True, to='app_articles.tagarticlesmodel')),
            ],
        ),
    ]
