# Generated by Django 5.1.3 on 2024-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='image_source',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Fonte da Imagem'),
        ),
        migrations.AddField(
            model_name='articlesmodel',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='É VIP'),
        ),
        migrations.AddField(
            model_name='articlesmodel',
            name='research_sources',
            field=models.TextField(blank=True, null=True, verbose_name='Fontes de Pesquisa'),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
    ]
