# Generated by Django 5.1.3 on 2024-12-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0002_articlesmodel_image_source_articlesmodel_is_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='image_source',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Fonte da Imagem'),
        ),
    ]
