# Generated by Django 5.1.3 on 2025-01-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0003_alter_articlesmodel_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='app_articles.categoryarticlesmodel'),
        ),
    ]
