# Generated by Django 5.1.7 on 2025-04-03 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiloModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoBiologicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabitatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoGeograficaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReinoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAmeacaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieMarinhaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comum', models.CharField(max_length=100, verbose_name='Nome Comum')),
                ('nome_cientifico', models.CharField(max_length=150, unique=True, verbose_name='Nome Científico')),
                ('imagem_principal', models.ImageField(blank=True, help_text='Imagem principal da espécie', null=True, upload_to='especies/', verbose_name='Imagem representativa')),
                ('classe', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.CharField(blank=True, max_length=100, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('profundidade_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('profundidade_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validado', models.BooleanField(default=False)),
                ('especialista_validacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_validacao', models.DateField(blank=True, null=True)),
                ('tamanho_medio', models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento médio em centímetros', max_digits=6, null=True, verbose_name='Tamanho médio (cm)')),
                ('tamanho_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento máximoo em centímetros', max_digits=6, null=True, verbose_name='Tamanho máximo (cm)')),
                ('importancia_economica', models.BooleanField(default=False, verbose_name='Importância Econômica')),
                ('permitida_pesca', models.BooleanField(default=True, verbose_name='Permitida para Pesca')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Geral')),
                ('comportamento', models.TextField(blank=True, null=True, verbose_name='Comportamento e Alimentação')),
                ('epoca_reproducao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Época de Reprodução')),
                ('fonte_pesquisa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte da Informação')),
                ('link_referencia', models.URLField(blank=True, null=True, verbose_name='Link da Referência')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('especies_relacionadas', models.ManyToManyField(blank=True, to='app_especies_maritimas.especiemarinhamodel')),
                ('filo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_especies_maritimas.filomodel')),
                ('grupo_biologico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_especies_maritimas.grupobiologicomodel')),
                ('habitat', models.ManyToManyField(blank=True, to='app_especies_maritimas.habitatmodel')),
                ('reino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_especies_maritimas.reinomodel')),
            ],
            options={
                'ordering': ['nome_cientifico'],
                'get_latest_by': 'data_ultima_alteracao',
            },
        ),
        migrations.CreateModel(
            name='ImagemEspecieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='especies/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('credito', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.especiemarinhamodel')),
            ],
        ),
        migrations.CreateModel(
            name='NomeComumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idioma', models.CharField(default='pt', max_length=50)),
                ('regiao', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.especiemarinhamodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaBibliograficaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.especiemarinhamodel')),
            ],
        ),
        migrations.CreateModel(
            name='DistribuicaoGeograficaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.especiemarinhamodel')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_especies_maritimas.regiaogeograficamodel')),
            ],
        ),
        migrations.AddField(
            model_name='filomodel',
            name='reino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.reinomodel'),
        ),
        migrations.CreateModel(
            name='StatusConservacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('iucn', 'Lista Vermelha da IUCN'), ('brasil', 'Lista Nacional do ICMBio'), ('estadual', 'Lista Estadual')], default='iucn', max_length=50)),
                ('status', models.CharField(choices=[('LC', 'Pouco Preocupante (LC - Least Concern)'), ('NT', 'Quase Ameaçado (NT - Near Threatened)'), ('VU', 'Vulnerável (VU - Vulnerable)'), ('EN', 'Em Perigo (EN - Endangered)'), ('CR', 'Criticamente Ameaçado (CR - Critically Endangered)'), ('EW', 'Extinto na Natureza (EW - Extinct in the Wild)'), ('EX', 'Extinto (EX - Extinct)'), ('DD', 'Dados Deficientes (DD - Data Deficient)'), ('NE', 'Não Avaliado (NE - Not Evaluated)')], max_length=5)),
                ('ano_avaliacao', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.especiemarinhamodel')),
            ],
            options={
                'verbose_name': 'Status de Conservação',
                'verbose_name_plural': 'Status de Conservação',
                'ordering': ['-ano_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='AmeacaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('gravidade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_especies_maritimas.especiemarinhamodel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_especies_maritimas.tipoameacamodel')),
            ],
        ),
        migrations.CreateModel(
            name='UsoCulinarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200, verbose_name='Nome da Receita')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('principal', 'Prato Principal'), ('acompanhamento', 'Acompanhamento'), ('sobremesa', 'Sobremesa'), ('outro', 'Outro')], default='principal', max_length=50, verbose_name='Tipo de Receita')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('chef', 'Nível Chef')], default='medio', max_length=50, verbose_name='Nível de Dificuldade')),
                ('tempo_preparo', models.PositiveIntegerField(help_text='Tempo total em minutos', verbose_name='Tempo de Preparo (minutos)')),
                ('porcoes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rendimento (porções)')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('modo_preparo', models.TextField(verbose_name='Modo de Preparo')),
                ('dicas', models.TextField(blank=True, null=True, verbose_name='Dicas e Variações')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/', verbose_name='Foto da Receita Pronta')),
                ('fonte', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonte da Receita')),
                ('link_referencia', models.URLField(blank=True, null=True, verbose_name='Link da Referência')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='app_especies_maritimas.especiemarinhamodel', verbose_name='Espécie Marinha')),
            ],
            options={
                'verbose_name': 'Uso Culinário',
                'verbose_name_plural': 'Usos Culinários',
                'ordering': ['nome_receita'],
            },
        ),
        migrations.AddIndex(
            model_name='especiemarinhamodel',
            index=models.Index(fields=['nome_cientifico'], name='app_especie_nome_ci_fd1287_idx'),
        ),
        migrations.AddIndex(
            model_name='especiemarinhamodel',
            index=models.Index(fields=['nome_comum'], name='app_especie_nome_co_eb6ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='usoculinariomodel',
            index=models.Index(fields=['nome_receita'], name='app_especie_nome_re_297e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='usoculinariomodel',
            index=models.Index(fields=['especie'], name='app_especie_especie_7d0486_idx'),
        ),
    ]
