# Generated by Django 5.1.7 on 2025-04-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_especies_maritimas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiemarinhamodel',
            name='classe',
            field=models.CharField(blank=True, choices=[('actinopterygii', 'Actinopterygii (Peixes ósseos)'), ('chondrichthyes', 'Chondrichthyes (Peixes cartilaginosos)'), ('malacostraca', 'Malacostraca (Crustáceos)')], max_length=100, null=True, verbose_name='Classe Taxonômica'),
        ),
        migrations.AlterField(
            model_name='especiemarinhamodel',
            name='familia',
            field=models.CharField(blank=True, choices=[('serranidae', 'Serranidae (Garoupas)'), ('penaeidae', 'Penaeidae (Camarões peneídeos)'), ('delphinidae', 'Delphinidae (Golfinhos)')], max_length=100, null=True, verbose_name='Família Taxonômica'),
        ),
        migrations.AlterField(
            model_name='especiemarinhamodel',
            name='ordem',
            field=models.CharField(blank=True, choices=[('perciformes', 'Perciformes'), ('decapoda', 'Decapoda'), ('cetacea', 'Cetacea')], max_length=100, null=True, verbose_name='Ordem Taxonômica'),
        ),
    ]
