# Generated by Django 5.1.7 on 2025-04-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_especies_maritimas', '0002_alter_especiemarinhamodel_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ameacamodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameaça', to='app_especies_maritimas.especiemarinhamodel'),
        ),
        migrations.AlterField(
            model_name='imagemespeciemodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app_especies_maritimas.especiemarinhamodel'),
        ),
        migrations.AlterField(
            model_name='nomecomummodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomes_comuns', to='app_especies_maritimas.especiemarinhamodel'),
        ),
    ]
