# Generated by Django 5.1.7 on 2025-04-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_especies_maritimas', '0004_filomodel_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ameacamodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameacas', to='app_especies_maritimas.especiemarinhamodel'),
        ),
        migrations.AlterField(
            model_name='distribuicaogeograficamodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicao_geografica', to='app_especies_maritimas.especiemarinhamodel'),
        ),
        migrations.AlterField(
            model_name='referenciabibliograficamodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_bibliograficas', to='app_especies_maritimas.especiemarinhamodel'),
        ),
        migrations.AlterField(
            model_name='regiaogeograficamodel',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='statusconservacaomodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_conservacao', to='app_especies_maritimas.especiemarinhamodel'),
        ),
    ]
