# Generated by Django 5.1.7 on 2025-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='recebe_seguro',
            field=models.CharField(blank=True, choices=[('Não Recebe', 'Não Recebe'), ('Recebe', 'Recebe'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True),
        ),
    ]
