# Generated by Django 5.1.3 on 2025-01-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0009_alter_associacaomodel_diretores_and_more'),
        ('app_associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associados_associacao', to='app_associacao.associacaomodel', verbose_name='Associação'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='municipio_circunscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipios_associados', to='app_associacao.municipiosmodel', verbose_name='Município de Circunscrição/Atuação'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='reparticao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparticoes_associados', to='app_associacao.reparticoesmodel', verbose_name='Repartição'),
        ),
    ]
