# Generated by Django 5.1.3 on 2025-01-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0002_alter_associadomodel_associacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='recebe_seguro',
            field=models.CharField(blank=True, choices=[('Não Recebe', 'Não Recebe'), ('A partir de Dez', 'A partir de Dez'), ('A partir de Jan', 'A partir de Jan'), ('A partir de Fev', 'A partir de Fev'), ('A partir de Março', 'A partir de Março'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True),
        ),
    ]
