# Generated by Django 5.1.7 on 2025-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0002_alter_associadomodel_recebe_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='bolsa_familia',
            field=models.CharField(blank=True, choices=[('Já recebeu', 'Já recebeu'), ('Nunca recebeu', 'Nunca recebeu'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Bolsa Família'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='comercializa_produtos',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Comercializa Produtos'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='relacao_trabalho',
            field=models.CharField(blank=True, choices=[('Indicidual Autônomo', 'Individual Autônomo'), ('Economia Familiar', 'Economia Familiar'), ('Regime de Parceria', 'Regime de Parceria'), ('Não declarado', 'Não declarado')], max_length=255, null=True, verbose_name='Relação de Trabalho'),
        ),
    ]
