# Generated by Django 5.1.3 on 2025-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0003_alter_associadomodel_recebe_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='senha_site',
            field=models.CharField(blank=True, help_text='Senha criptografada para segurança.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie1',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea'), ('Anchova', 'Anchova'), ('Atum', 'Atum'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cação', 'Cação'), ('Cavala', 'Cavala'), ('Corvina', 'Corvina'), ('Garoupa', 'Garoupa'), ('Linguado', 'Linguado'), ('Marisco', 'Marisco'), ('Pampo', 'Pampo'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Tainha', 'Tainha'), ('Xerelete', 'Xerelete'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 1'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie2',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea'), ('Anchova', 'Anchova'), ('Atum', 'Atum'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cação', 'Cação'), ('Cavala', 'Cavala'), ('Corvina', 'Corvina'), ('Garoupa', 'Garoupa'), ('Linguado', 'Linguado'), ('Marisco', 'Marisco'), ('Pampo', 'Pampo'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Tainha', 'Tainha'), ('Xerelete', 'Xerelete'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 2'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie3',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea'), ('Anchova', 'Anchova'), ('Atum', 'Atum'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cação', 'Cação'), ('Cavala', 'Cavala'), ('Corvina', 'Corvina'), ('Garoupa', 'Garoupa'), ('Linguado', 'Linguado'), ('Marisco', 'Marisco'), ('Pampo', 'Pampo'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Tainha', 'Tainha'), ('Xerelete', 'Xerelete'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 3'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie4',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea'), ('Anchova', 'Anchova'), ('Atum', 'Atum'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cação', 'Cação'), ('Cavala', 'Cavala'), ('Corvina', 'Corvina'), ('Garoupa', 'Garoupa'), ('Linguado', 'Linguado'), ('Marisco', 'Marisco'), ('Pampo', 'Pampo'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Tainha', 'Tainha'), ('Xerelete', 'Xerelete'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 4'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie5',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea'), ('Anchova', 'Anchova'), ('Atum', 'Atum'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cação', 'Cação'), ('Cavala', 'Cavala'), ('Corvina', 'Corvina'), ('Garoupa', 'Garoupa'), ('Linguado', 'Linguado'), ('Marisco', 'Marisco'), ('Pampo', 'Pampo'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Tainha', 'Tainha'), ('Xerelete', 'Xerelete'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 5'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Associado Lista Ativo(a)', 'Associado Lista Ativo(a)'), ('Associado Lista Aposentado(a)', 'Associado  Lista Aposentado(a)'), ('Candidato(a)', 'Candidato(a)'), ('Cliente Especial', 'Cliente Especial'), ('Desassociado(a)', 'Desassociado(a)')], default='Candidato(a)', max_length=40, null=True, verbose_name='Status'),
        ),
    ]
