# Generated by Django 5.1.3 on 2025-01-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0004_associadomodel_senha_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
