# Generated by Django 5.1.7 on 2025-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0004_alter_associadomodel_comercializa_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Associado Lista Ativo(a)', 'Associado Lista Ativo(a)'), ('Associado Lista Aposentado(a)', 'Associado Lista Aposentado(a)'), ('Candidato(a)', 'Candidato(a)'), ('Cliente Especial', 'Cliente Especial'), ('Desassociado(a)', 'Desassociado(a)')], default='Candidato(a)', max_length=40, null=True, verbose_name='Status'),
        ),
    ]
