# Generated by Django 5.1.7 on 2025-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0006_associadomodel_ja_recebeu_defeso_algumavez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='ja_recebeu_defeso_algumavez',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Já Recebeu Seguro Defeso Alguma Vez?'),
        ),
    ]
