# Generated by Django 5.1.7 on 2025-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0007_alter_associadomodel_ja_recebeu_defeso_algumavez'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='outra_fonte_renda',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=250, null=True, verbose_name='Possui outra Fonte de renda?'),
        ),
    ]
