# Generated by Django 5.1.7 on 2025-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0008_associadomodel_outra_fonte_renda'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='casa_onde_mora',
            field=models.CharField(blank=True, choices=[('Mora em casa prórpia', 'Mora em pasa prórpia'), ('Mora em casa augada', 'Mora em casa augada'), ('Mora em casa cedida', 'Mora em casa cedida'), ('Mora em casa de terceiros', 'Mora em casa de terceiros'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Casa Onde Mora'),
        ),
    ]
