# Generated by Django 5.1.7 on 2025-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0009_associadomodel_casa_onde_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='apelido',
            field=models.CharField(blank=True, help_text='Apelido Carinhoso.', max_length=80, null=True, verbose_name='Apelido Carinhoso'),
        ),
    ]
