# Generated by Django 5.1.7 on 2025-06-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0011_alter_associadomodel_outra_fonte_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='outra_fonte_renda',
            field=models.CharField(blank=True, choices=[('Não Possui', 'Não Possui'), ('Aposentadoria (INSS)', 'Aposentadoria (INSS)'), ('MEI', 'MEI'), ('Sócio de Empresa', 'Sócio de Empresa'), ('CLT', 'CLT'), ('Servidor Público', 'Servidor Público'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=250, null=True, verbose_name='Possui outra Fonte de renda?'),
        ),
    ]
