# Generated by Django 5.1.7 on 2025-06-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0012_alter_associadomodel_outra_fonte_renda'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='cnh_data_validae',
            field=models.DateField(blank=True, null=True, verbose_name='Data Validade da CNH'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='cnh_uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='CNH UF'),
        ),
    ]
