# Generated by Django 5.1.7 on 2025-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0013_associadomodel_cnh_data_validae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associadomodel',
            old_name='cnh_data_validae',
            new_name='cnh_data_validade',
        ),
    ]
