# Generated by Django 5.1.7 on 2025-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0014_rename_cnh_data_validae_associadomodel_cnh_data_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='preco1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço por Kg - Espécie 1 (R$)'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='preco2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço por Kg - Espécie 2 (R$)'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='preco3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço por Kg - Espécie 3 (R$)'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='preco4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço por Kg - Espécie 4 (R$)'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='preco5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço por Kg - Espécie 5 (R$)'),
        ),
    ]
