# Generated by Django 5.1.7 on 2025-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0015_associadomodel_preco1_associadomodel_preco2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='especie1',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea (Phycis phycis)'), ('Anchova', 'Anchova (Pomatomus saltatrix)'), ('Atum', 'Atum (Thunnus spp.)'), ('Bagre', 'Bagre (Siluriformes)'), ('Baiacu', 'Baiacu (Tetraodontidae)'), ('Camarão Branco', 'Camarão Branco (Litopenaeus schmitti)'), ('Camarão Rosa', 'Camarão Rosa (Farfantepenaeus paulensis)'), ('Cação', 'Cação (Ginglymostomatidae)'), ('Cavala', 'Cavala (Scomberomorus cavalla)'), ('Corvina', 'Corvina (Micropogonias furnieri)'), ('Garoupa', 'Garoupa (Epinephelus marginatus)'), ('Linguado', 'Linguado (Paralichthys orbignyanus)'), ('Marisco', 'Marisco (Bivalvia)'), ('Pampo', 'Pampo (Trachinotus carolinus)'), ('Parati', 'Parati (Mugil curema)'), ('Pescada Olhuda', 'Pescada Olhuda (Cynoscion guatucupa)'), ('Pescada Branca', 'Pescada Branca (Cynoscion leiarchus)'), ('Robalo', 'Robalo (Centropomus undecimalis)'), ('Sardinha', 'Sardinha (Sardinella brasiliensis)'), ('Tainha', 'Tainha (Mugil liza)'), ('Xerelete', 'Xerelete (Caranx hippos)'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 1'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie2',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea (Phycis phycis)'), ('Anchova', 'Anchova (Pomatomus saltatrix)'), ('Atum', 'Atum (Thunnus spp.)'), ('Bagre', 'Bagre (Siluriformes)'), ('Baiacu', 'Baiacu (Tetraodontidae)'), ('Camarão Branco', 'Camarão Branco (Litopenaeus schmitti)'), ('Camarão Rosa', 'Camarão Rosa (Farfantepenaeus paulensis)'), ('Cação', 'Cação (Ginglymostomatidae)'), ('Cavala', 'Cavala (Scomberomorus cavalla)'), ('Corvina', 'Corvina (Micropogonias furnieri)'), ('Garoupa', 'Garoupa (Epinephelus marginatus)'), ('Linguado', 'Linguado (Paralichthys orbignyanus)'), ('Marisco', 'Marisco (Bivalvia)'), ('Pampo', 'Pampo (Trachinotus carolinus)'), ('Parati', 'Parati (Mugil curema)'), ('Pescada Olhuda', 'Pescada Olhuda (Cynoscion guatucupa)'), ('Pescada Branca', 'Pescada Branca (Cynoscion leiarchus)'), ('Robalo', 'Robalo (Centropomus undecimalis)'), ('Sardinha', 'Sardinha (Sardinella brasiliensis)'), ('Tainha', 'Tainha (Mugil liza)'), ('Xerelete', 'Xerelete (Caranx hippos)'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 2'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie3',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea (Phycis phycis)'), ('Anchova', 'Anchova (Pomatomus saltatrix)'), ('Atum', 'Atum (Thunnus spp.)'), ('Bagre', 'Bagre (Siluriformes)'), ('Baiacu', 'Baiacu (Tetraodontidae)'), ('Camarão Branco', 'Camarão Branco (Litopenaeus schmitti)'), ('Camarão Rosa', 'Camarão Rosa (Farfantepenaeus paulensis)'), ('Cação', 'Cação (Ginglymostomatidae)'), ('Cavala', 'Cavala (Scomberomorus cavalla)'), ('Corvina', 'Corvina (Micropogonias furnieri)'), ('Garoupa', 'Garoupa (Epinephelus marginatus)'), ('Linguado', 'Linguado (Paralichthys orbignyanus)'), ('Marisco', 'Marisco (Bivalvia)'), ('Pampo', 'Pampo (Trachinotus carolinus)'), ('Parati', 'Parati (Mugil curema)'), ('Pescada Olhuda', 'Pescada Olhuda (Cynoscion guatucupa)'), ('Pescada Branca', 'Pescada Branca (Cynoscion leiarchus)'), ('Robalo', 'Robalo (Centropomus undecimalis)'), ('Sardinha', 'Sardinha (Sardinella brasiliensis)'), ('Tainha', 'Tainha (Mugil liza)'), ('Xerelete', 'Xerelete (Caranx hippos)'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 3'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie4',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea (Phycis phycis)'), ('Anchova', 'Anchova (Pomatomus saltatrix)'), ('Atum', 'Atum (Thunnus spp.)'), ('Bagre', 'Bagre (Siluriformes)'), ('Baiacu', 'Baiacu (Tetraodontidae)'), ('Camarão Branco', 'Camarão Branco (Litopenaeus schmitti)'), ('Camarão Rosa', 'Camarão Rosa (Farfantepenaeus paulensis)'), ('Cação', 'Cação (Ginglymostomatidae)'), ('Cavala', 'Cavala (Scomberomorus cavalla)'), ('Corvina', 'Corvina (Micropogonias furnieri)'), ('Garoupa', 'Garoupa (Epinephelus marginatus)'), ('Linguado', 'Linguado (Paralichthys orbignyanus)'), ('Marisco', 'Marisco (Bivalvia)'), ('Pampo', 'Pampo (Trachinotus carolinus)'), ('Parati', 'Parati (Mugil curema)'), ('Pescada Olhuda', 'Pescada Olhuda (Cynoscion guatucupa)'), ('Pescada Branca', 'Pescada Branca (Cynoscion leiarchus)'), ('Robalo', 'Robalo (Centropomus undecimalis)'), ('Sardinha', 'Sardinha (Sardinella brasiliensis)'), ('Tainha', 'Tainha (Mugil liza)'), ('Xerelete', 'Xerelete (Caranx hippos)'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 4'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie5',
            field=models.CharField(blank=True, choices=[('Abrótea', 'Abrótea (Phycis phycis)'), ('Anchova', 'Anchova (Pomatomus saltatrix)'), ('Atum', 'Atum (Thunnus spp.)'), ('Bagre', 'Bagre (Siluriformes)'), ('Baiacu', 'Baiacu (Tetraodontidae)'), ('Camarão Branco', 'Camarão Branco (Litopenaeus schmitti)'), ('Camarão Rosa', 'Camarão Rosa (Farfantepenaeus paulensis)'), ('Cação', 'Cação (Ginglymostomatidae)'), ('Cavala', 'Cavala (Scomberomorus cavalla)'), ('Corvina', 'Corvina (Micropogonias furnieri)'), ('Garoupa', 'Garoupa (Epinephelus marginatus)'), ('Linguado', 'Linguado (Paralichthys orbignyanus)'), ('Marisco', 'Marisco (Bivalvia)'), ('Pampo', 'Pampo (Trachinotus carolinus)'), ('Parati', 'Parati (Mugil curema)'), ('Pescada Olhuda', 'Pescada Olhuda (Cynoscion guatucupa)'), ('Pescada Branca', 'Pescada Branca (Cynoscion leiarchus)'), ('Robalo', 'Robalo (Centropomus undecimalis)'), ('Sardinha', 'Sardinha (Sardinella brasiliensis)'), ('Tainha', 'Tainha (Mugil liza)'), ('Xerelete', 'Xerelete (Caranx hippos)'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 5'),
        ),
    ]
