# Generated by Django 5.1.7 on 2025-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0016_alter_associadomodel_especie1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrechoPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='petrechos_pesca',
            field=models.ManyToManyField(blank=True, to='app_associados.petrechopesca', verbose_name='Petrechos de Pesca'),
        ),
    ]
